### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by DaeronAlagos** [BSData/warcaster-neo-mechanika#3]
Hi, I'm Daeron,
I'd like to contribute to this repository, because the original author is MIA on discord, and I am an active player of the game.

CC: @BSData/owners

**Comment by amis92** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/1235160397)
:robot: Invited @DaeronAlagos with **push** access. Invite can be accepted on https://github.com/BSData/warcaster-neo-mechanika/invitations
